In [ ]:
import numpy as np

arr1=np.array([1,4,7,3,8])
print("My array is: ",arr1)

myList=[3,8,5,3]
print("MyList is: ",myList)

My array is:  [1 4 7 3 8]
MyList is:  [3, 8, 5, 3]


In [2]:
%timeit [i*2 for i in range(1,21)]

610 ns ± 51.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [3]:
%timeit np.arange(1,21)*2

2.59 μs ± 389 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
import numpy as np

# arr=np.array([3,5,7,9])
# in1="Shivam"
# print(arr)
# print(type(arr))
# print(arr.ndim)
# arr



In [5]:
arr2=np.array([[3,5,7,9],[5,3,7,2],[2,5,8,2]])
# # arr2=np.array([[4,4,6],[3,8,9]])
# arr2=np.array([[[3,8,3],[4,5,6],[7,9,1]]])

# arr2
print(arr2)
print(arr2.ndim)

[[3 5 7 9]
 [5 3 7 2]
 [2 5 8 2]]
2


In [6]:
arr3=np.array([[[5,3,7,2],[2,5,8,2],[4,5,7,2]]])

# arr2
print(arr3)
print(arr3.ndim)

[[[5 3 7 2]
  [2 5 8 2]
  [4 5 7 2]]]
3


In [7]:
arrN=np.array([1,3,5,6,5],ndmin=10)
# arr2
print(arrN)
print(arrN.ndim)

[[[[[[[[[[1 3 5 6 5]]]]]]]]]]
10


In [8]:
import numpy as np

zerosArr1=np.zeros(8)
zerosArr2=np.zeros((4,3))

print(zerosArr1)
print("--------------")
print(zerosArr2)

[0. 0. 0. 0. 0. 0. 0. 0.]
--------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
zerosArr1=np.ones(4)
zerosArr2=np.ones((4,3))

print(zerosArr1)
print("--------------")
print(zerosArr2)

[1. 1. 1. 1.]
--------------
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
arrEmp=np.empty((2,3)) # Random garbage values
print(arrEmp)

# arrRange=np.arange(4,15,2)
# print(arrRange)
arrRange=np.arange(5)*2
arrRange

[[ 1.79769313e+308 -1.79769313e+308  2.00000000e+000]
 [ 2.22044605e-016  2.22507386e-308  4.94065646e-324]]


array([0, 2, 4, 6, 8])

In [11]:
# arrDiogonal=np.eye(2)
# print(arrDiogonal)

arrDiogonal=np.eye(3,4)
arrDiogonal

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [12]:
arr_lin=np.linspace(19,20,num=10)
arr_lin

array([19.        , 19.11111111, 19.22222222, 19.33333333, 19.44444444,
       19.55555556, 19.66666667, 19.77777778, 19.88888889, 20.        ])

In [13]:
# var1=np.random.rand(5)*10
# var2=np.random.rand(3,3)
# var3=np.random.randn(15)
var4=np.random.randn(3,4)

# print("Random 1d Array Between 0 to 1:",var1)
# print("Random 2d Array Between 0 to 1:",var2)
# print("Random 1d Array Between closed to zero Negative Positive:",var3)
# print("Random 2d Array Between closed to zero Negative Positive:",var4)


In [14]:
# var5=np.random.ranf(15)
# var6=np.random.ranf((4,5))
var7=np.random.randint(4,56,15)

# print("Random 1d Array Between [0,1):",var5)
# print("Random 2d Array Between [0,1):",var6)
print("Random integer 1d Array Between 4 to 10:",var7)

Random integer 1d Array Between 4 to 10: [ 8 51 26  8 15 12 26 44  4  5  4 22 55 20 47]


In [24]:
# arr2=np.array([[1,4,5,6],[3,5,6,8],[5,8,7,8]])
# arr2=np.array([1,4,5,6],[3,5,6,8],[5,8,7,8])
arr2=np.array([
    [4,6,7],
    [6,9,8],
    [9,9,18]
])

print(arr2)

[[ 4  6  7]
 [ 6  9  8]
 [ 9  9 18]]
